name: 'Deployment'

on:
  push:

env:
  ACCESS: ${{ secrets.AWS_ACCESS_KEY }}
  SECRET: ${{ secrets.AWS_SECRET_KEY }}
  PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY}}

jobs:
  terratest:
    name: 'TerraTest'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run python
      run: |
        echo "$PRIVATE_KEY" > private.pem && chmod 600 private.pem
        ls -al
        # chmod +x script.sh
        ./script.sh ec2-52-35-174-39.us-west-2.compute.amazonaws.com $ACCESS $SECRET
