name: 'Deployment'

on:
  workflow_dispatch:

env:
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
  USER: ec2-user
  PORT: 22

jobs:
  terratest:
    name: 'TerraTest'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run python
      run: python3 app.py
      