name: 'Deployment'

on:
  push:

env:
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
  USER: ec2-user
  PORT: 22

jobs:
  terratest:
    name: 'TerraTest'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run python
      run: python3 app.py

    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_ACCESS_KEY }}
        username: fdsf
        key: ${{ secrets.AWS_SECRET_KEY }}
        port: 22
        script: |
          sudo apt update
          sudo apt install git
    #       git clone -b dev https://github.com/radyas/terraform-aws.git
    #       cd terraform-aws/api
    #       ls -al
    #       pip3 install -r requirements.txt
    #       bash
    #       flask run --host 0.0.0.0
      